'use strict';
const icons={
 home:'<path d="m3 10 9-7 9 7v10a1 1 0 0 1-1 1h-5v-7H9v7H4a1 1 0 0 1-1-1Z"/>',
 grid:'<rect x="3" y="3" width="7" height="7" rx="1.5"/><rect x="14" y="3" width="7" height="7" rx="1.5"/><rect x="3" y="14" width="7" height="7" rx="1.5"/><rect x="14" y="14" width="7" height="7" rx="1.5"/>',
 inbox:'<path d="M4 4h16l2 11v5H2v-5Z"/><path d="M2 15h6l2 3h4l2-3h6"/>',
 tasks:'<rect x="5" y="4" width="15" height="17" rx="2"/><path d="M9 2h7v4H9zM9 11l1 1 2-2m3 1h2m-8 5 1 1 2-2m3 1h2"/>',
 repeat:'<path d="m17 2 4 4-4 4M3 11V8a2 2 0 0 1 2-2h16M7 22l-4-4 4-4m14-1v3a2 2 0 0 1-2 2H3"/>',
 plug:'<path d="m7 7 10 10M7 7l-3 3 10 10 3-3M11 3 7 7m14 6-4 4M5 17l-3 3m9-12 5-5m-1 9 5-5"/>',
 settings:'<path d="m9 3-.5 3-2 1L4 6 2 10l2.5 2v2L2 16l2 4 2.5-1 2 1 .5 2h5l.5-2 2-1 2.5 1 2-4-2.5-2v-2L22 10l-2-4-2.5 1-2-1-.5-3Z"/><circle cx="12" cy="12" r="3"/>',
 search:'<circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/>',
 plus:'<path d="M12 5v14M5 12h14"/>',
 chevron:'<path d="m9 5 7 7-7 7"/>',
 down:'<path d="m7 10 5 5 5-5"/>',
 arrow:'<path d="M5 12h14m-5-5 5 5-5 5"/>',
 up:'<path d="M12 19V5m-6 6 6-6 6 6"/>',
 check:'<path d="m5 12 4 4L19 6"/>',
 clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',
 spark:'<path d="m12 3 2.5 6.5L21 12l-6.5 2.5L12 21l-2.5-6.5L3 12l6.5-2.5ZM20 2v4m-2-2h4"/>',
 code:'<path d="m8 6-6 6 6 6m8-12 6 6-6 6m-3-14-2 16"/>',
 brush:'<path d="m10 14 9-11 3 3-11 9"/><path d="M10 14c-5-3-7 2-6 4l-2 3c7 1 10-3 8-7Z"/>',
 globe:'<circle cx="12" cy="12" r="9"/><ellipse cx="12" cy="12" rx="4" ry="9"/><path d="M3 12h18"/>',
 trend:'<path d="m3 17 6-6 4 3 8-10m-6 0h6v6"/>',
 shield:'<path d="m12 2 8 4v7c0 5-8 9-8 9s-8-4-8-9V6Z"/><path d="m8 12 3 3 5-6"/>',
 screen:'<rect x="2" y="3" width="20" height="14" rx="2"/><path d="M8 21h8m-4-4v4"/>',
 list:'<path d="M9 6h12M9 12h12M9 18h12M3 6h1M3 12h1M3 18h1"/>',
 org:'<rect x="9" y="2" width="6" height="5" rx="1"/><rect x="2" y="17" width="6" height="5" rx="1"/><rect x="16" y="17" width="6" height="5" rx="1"/><path d="M12 7v5M5 17v-5h14v5"/>',
 pause:'<path d="M8 5v14M16 5v14"/>',
 play:'<path d="m7 4 14 8-14 8Z"/>',
 expand:'<path d="M8 3H3v5m13-5h5v5M3 16v5h5m13-5v5h-5"/>',
 close:'<path d="m6 6 12 12M6 18 18 6"/>',
 moon:'<path d="M21 13A9 9 0 0 1 11 3a9 9 0 1 0 10 10Z"/>',
 file:'<path d="M14 2H5v20h14V7Zm0 0v5h5M8 12h8m-8 4h6"/>',
 download:'<path d="M12 3v12m-5-5 5 5 5-5M3 16v5h18v-5"/>',
 git:'<circle cx="6" cy="5" r="3"/><circle cx="6" cy="19" r="3"/><circle cx="18" cy="6" r="3"/><path d="M6 8v8m12-7c0 5-12 1-12 7"/>',
 layout:'<rect x="2" y="3" width="20" height="18" rx="2"/><path d="M2 8h20M8 8v13"/>',
 bolt:'<path d="m13 2-9 12h7l-1 8 10-13h-8Z"/>',
 menu:'<path d="M4 6h16M4 12h16M4 18h16"/>',
 chat:'<path d="M4 3h16v14H9l-5 4Z"/>',
 heart:'<path d="M12 21 3 12C-2 4 8-2 12 6c4-8 14-2 9 6Z"/>'
};
const icon=(name,cls='')=>`<svg class="${cls}" viewBox="0 0 24 24" aria-hidden="true">${icons[name]||icons.spark}</svg>`;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const makeBot=(id,name,role,avatar,color,status,doing,skill,bio)=>({id,name,role,avatar,color,status,doing,skill,bio,model:id==='byte'?'Codex':'Claude',messages:[]});
const bots=[
 makeBot('focx','Focx','Chief of Staff',0,'#e5a876','working','Keeping things moving','spark','The big-picture thinker with a soft spot for a good checklist. I keep your team focused on launching Connect.'),
 makeBot('byte','Byte','Developer',1,'#8ab6da','working','Building onboarding','code','Coffee optional. Clean code essential. I turn your team’s ideas into working product experiences.'),
 makeBot('pixel','Pixel','Designer',2,'#b8a0d2','waiting','Needs your feedback','brush','Equal parts systems thinker and pixel perfectionist. I keep Connect feeling unmistakably Focx.'),
 makeBot('bloom','Bloom','Growth',3,'#b5c790','working','Planning the launch','trend','Small experiments, meaningful growth. I help the right people discover and fall in love with Connect.'),
 makeBot('patch','Patch','Quality Assurance',4,'#c7b599','idle','All checks passed','shield','Your lovingly skeptical teammate. I check the details, find the edge cases, and give every release a second look.'),
 makeBot('scout','Scout','Researcher',5,'#d6a0b5','working','Exploring opportunities','globe','Curiosity is my favorite skill. I bring the useful findings back to the den, with sources and a point of view.')
];
const tasks=[
 {id:108,title:'Explore Connect referral ideas',bot:'scout',status:'todo',priority:'Normal'},
 {id:109,title:'Draft the launch announcement',bot:'bloom',status:'todo',priority:'High'},
 {id:104,title:'Build the welcome flow',bot:'byte',status:'doing',priority:'High'},
 {id:105,title:'Refine the person profile',bot:'pixel',status:'doing',priority:'Normal'},
 {id:106,title:'Map the first launch channels',bot:'bloom',status:'doing',priority:'Normal'},
 {id:101,title:'Review connection reminders',bot:'patch',status:'done',priority:'Normal'},
 {id:102,title:'Summarize the customer interviews',bot:'scout',status:'done',priority:'Normal'},
 {id:103,title:'Plan this week’s priorities',bot:'focx',status:'done',priority:'Normal'}
];
const approvals=[
 {id:'design',bot:'pixel',title:'A fresh welcome for Connect',description:'The welcome flow is ready for a look. Three focused screens, the existing Focx components, and a little more personality.',label:'Design review',status:'pending',doc:'Connect · Welcome flow',body:'1. Welcome to Connect\nA calm introduction: “Make a little room for your people.” One primary action: Add your first person.\n\n2. Start with someone\nName and relationship are enough to begin. Additional context can come later.\n\n3. Your first small step\nChoose a thoughtful check-in or set a reminder. No contact upload required.\n\nReview focus: clarity, consistent components, accessible contrast, and a comfortable first action.'},
 {id:'launch',bot:'bloom',title:'Your first launch announcement',description:'A short, human introduction to Connect. Ready for your review before anything goes out.',label:'Copy review',status:'pending',doc:'Connect · Launch announcement',body:'Some relationships don’t need a grand gesture. Just a little more attention.\n\nMeet Connect by Focx. A thoughtful place to remember the little things, follow through, and make room for the people who matter.\n\nWe’re starting small, listening closely, and building with you.\n\nGet to know Connect.\n\nDraft only. Review the invitation link, audience, and product availability before publishing.'},
 {id:'plan',bot:'focx',title:'This week’s priorities, all lined up',description:'A small, focused plan for product, design, and growth. Give the team a direction.',label:'Plan review',status:'pending',doc:'Connect · Team priorities',body:'1. Product\nByte completes the welcome flow. Patch checks keyboard navigation, mobile layout, and failure states.\n\n2. Design\nPixel aligns the person profile and welcome screens with the Focx design system.\n\n3. Growth\nBloom drafts the launch announcement. Scout identifies three communities where Connect is a natural fit.\n\nYour decision\nReview the welcome flow first. It is the dependency for the next product demo.'}
];
const routines=[{id:1,name:'A good morning, on autopilot',prompt:'Summarize what the team shipped, flag blockers, and suggest my top three priorities.',schedule:'Every weekday · 8:00 AM',bot:'focx',enabled:true,icon:'spark'},{id:2,name:'The nightly quality patrol',prompt:'Review completed development tasks and prepare a quality report for the morning.',schedule:'Every day · 11:00 PM',bot:'patch',enabled:true,icon:'moon'},{id:3,name:'A little competitive curiosity',prompt:'Find relevant product updates and three useful growth opportunities for Connect.',schedule:'Every Monday · 9:00 AM',bot:'scout',enabled:false,icon:'globe'}];
const connections=[{id:'github',name:'GitHub',description:'Repos, pull requests, and all the little details.',icon:'git',connected:true},{id:'figma',name:'Figma',description:'A shared home for design and visual thinking.',icon:'layout',connected:true},{id:'posthog',name:'PostHog',description:'Turn product signals into better decisions.',icon:'trend',connected:false},{id:'browser',name:'Browser',description:'A window to research, tools, and the wider web.',icon:'globe',connected:true}];
let activity=[{bot:'byte',text:'Bringing the Connect welcome flow to life.',time:'Just now',chip:'welcome-flow.tsx',icon:'code'},{bot:'scout',text:'Found 3 communities worth exploring for launch.',time:'2m ago',chip:'Research notes',icon:'file'},{bot:'pixel',text:'The new welcome screens are ready for you.',time:'6m ago',chip:'3 screens to review',icon:'layout'},{bot:'patch',text:'Connection reminders passed the quality check.',time:'12m ago',chip:'All checks passed',icon:'check'}];
let view='den',selectedBot='focx',denMode='grid',paused=false,motion=true,typing=new Set(),toastTimer,avatarChoice=0,screenTaken=false,attachNext=false;
let nextTask=110;
const $=s=>document.querySelector(s);
const byId=id=>bots.find(b=>b.id===id)||bots[0];
const pending=()=>approvals.filter(a=>a.status==='pending');
const working=()=>bots.filter(b=>b.status==='working').length;
const done=()=>tasks.filter(t=>t.status==='done').length;
function avatar(bot,extra=''){return `<span class="avatar ${extra}" role="img" aria-label="${esc(bot.name)} fox" style="--avatar-x:${(bot.avatar%3)*50}%;--avatar-y:${Math.floor(bot.avatar/3)*100}%"></span>`}
const botStyle=b=>`--bot-color:${b.color};--delay:-${b.avatar*.7}s`;
function nav(name,title,ic,count){return `<button class="nav-item ${view===name?'active':''}" data-view="${name}" ${view===name?'aria-current="page"':''}>${icon(ic)}<span>${title}</span>${count?`<span class="nav-count">${count}</span>`:''}</button>`}
function sidebar(){ $('#sidebar').innerHTML=`<button class="brand" data-view="den" aria-label="Focx Bot home"><span class="brand-mark">f</span><span class="brand-name">focx <em>bot</em></span></button><button class="search-button" data-action="search">${icon('search')}<span>Find anything</span><kbd>⌘ K</kbd></button><nav class="navigation" aria-label="Workspace">${nav('den','The den','home')}${nav('inbox','Inbox','inbox',pending().length)}${nav('tasks','Tasks','tasks',tasks.filter(t=>t.status!=='done').length)}${nav('routines','Routines','repeat')}</nav><div class="sidebar-label">YOUR BOTS <button data-action="add-bot" aria-label="Add a bot">${icon('plus')}</button></div><div class="bot-roster">${bots.map(b=>`<button class="bot-nav ${view==='chat'&&selectedBot===b.id?'active':''}" data-bot="${b.id}">${avatar(b)}<span class="bot-nav-text"><strong>${esc(b.name)}</strong><small>${esc(b.role)}</small></span><i class="status-dot ${b.status}" title="${b.status}"></i></button>`).join('')}</div><div class="sidebar-bottom">${nav('connections','Connections','plug')}${nav('settings','Settings','settings')}<button class="workspace-select" data-action="workspace"><span class="workspace-monogram">F</span><span><strong>Focx workspace</strong><small>Ryan’s personal den</small></span>${icon('down')}</button></div>`; }
function toolbar(){const titles={den:'The den',inbox:'Inbox',tasks:'Tasks',routines:'Routines',connections:'Connections',settings:'Settings',chat:byId(selectedBot).name};$('#toolbar').innerHTML=`<div class="breadcrumb"><button class="icon-button mobile-menu" data-action="menu" aria-label="Toggle navigation">${icon('menu')}</button><span>Workspace</span>${icon('chevron')}<strong>${esc(titles[view])}</strong></div><div class="toolbar-actions"><button class="icon-button toolbar-helper" data-action="toggle-live" aria-label="${paused?'Resume':'Pause'} demo activity" title="${paused?'Resume':'Pause'} demo activity">${icon(paused?'play':'pause')}</button><button class="subtle-button" data-action="${view==='chat'?'screen':'invite-info'}">${icon(view==='chat'?'screen':'chat')}${view==='chat'?'Open computer':'Talk to Focx'}</button><button class="primary-button" data-action="${view==='tasks'?'add-task':view==='routines'?'add-routine':'add-bot'}">${icon('plus')}${view==='tasks'?'New task':view==='routines'?'New routine':'New bot'}</button></div>`;}
function heading(title,sub,eyebrow='YOUR WORKSPACE',right=''){return `<div class="page-heading"><div><div class="eyebrow">${eyebrow}</div><h1>${title}</h1><p>${sub}</p></div>${right}</div>`}
function composer(bot,team=false){return `<div class="composer-zone"><form class="composer" id="chat-form"><textarea id="message-input" rows="2" aria-label="Message ${esc(bot.name)}" placeholder="${team?'Give your team something to do…':`Message ${esc(bot.name)}…`}" maxlength="4000"></textarea><div class="composer-bottom"><div class="composer-tools"><button class="icon-button" type="button" data-action="attach" aria-label="Attach a demo brief" title="Attach a demo brief">${icon('plus')}</button><button type="button" class="composer-target" data-action="choose-target">${avatar(bot)}${esc(bot.name)}${icon('down')}</button><span>${team?'Chief of Staff':esc(bot.role)}</span><span id="attach-label"></span></div><button type="submit" class="send-button" aria-label="Send message">${icon('up')}</button></div></form><p class="composer-hint">A little direction goes a long way. <span>Enter to send · Shift + Enter for a new line</span></p></div>`}
function botCard(b){return `<button class="bot-card" data-bot="${b.id}" style="${botStyle(b)}"><span class="card-corner">${icon(b.skill)}</span>${avatar(b)}<strong>${esc(b.name)}</strong><span class="role">${esc(b.role)}</span><span class="bot-state ${b.status}">${icon(b.status==='working'?'spark':b.status==='waiting'?'clock':'check')}${esc(b.doing)}</span></button>`}
function den(){let body=denMode==='list'?`<div class="list-view">${bots.map(b=>`<button class="bot-row" data-bot="${b.id}" style="${botStyle(b)}">${avatar(b)}<div><strong>${esc(b.name)}</strong><small>${esc(b.role)}</small></div><span class="row-status">${esc(b.doing)}</span>${icon('chevron')}</button>`).join('')}</div>`:`<section class="den ${denMode==='org'?'is-org':''}" aria-label="Your bot team"><div class="den-topline"><span>FOCX / ${denMode==='org'?'COMPANY VIEW':'TEAM PRESENCE'}</span><span>${icon('bolt')} ${paused?'Taking a breather':'A little hive of activity'}</span></div>${denMode==='org'?'<div class="org-connectors" aria-hidden="true"></div>':''}<div class="bot-grid">${bots.map(botCard).join('')}</div><div class="den-caption">${icon('chat')} Click a teammate to see what they’re up to</div></section>`;
 $('#main').innerHTML=`<div class="main-content">${heading('The den','Good things happen when your team clicks.','GOOD EVENING, RYAN',`<button class="live-tag" data-action="toggle-live"><i class="status-dot"></i>${paused?'Activity paused':`${working()} bots working`}</button>`)}<div class="view-controls"><div class="segmented" aria-label="Team view">${[['grid','grid','Team'],['org','org','Company'],['list','list','List']].map(([id,ic,text])=>`<button class="${denMode===id?'active':''}" data-mode="${id}" aria-pressed="${denMode===id}">${icon(ic)}${text}</button>`).join('')}</div><span class="section-label">${bots.length} teammates. One direction.</span></div>${body}<div class="team-summary"><div class="summary-metric"><label>${icon('check')}Tasks completed</label><div class="metric-value">${done()}<span>Good progress</span></div></div><div class="summary-metric"><label>${icon('bolt')}In motion</label><div class="metric-value">${tasks.filter(t=>t.status==='doing').length}<span>Across your team</span></div></div><div class="summary-metric"><label>${icon('clock')}Needs your eye</label><div class="metric-value">${pending().length}<span style="color:#b8a083">Ready to review</span></div></div></div></div>${composer(bots[0],true)}`;}
function activityPanel(){ $('#activity').innerHTML=`<div class="panel-heading"><h2>Happening now</h2><span class="pulse-icon" aria-label="Simulated activity"><i></i><i></i><i></i></span></div><div class="activity-list">${activity.slice(0,4).map(a=>`<div class="activity-item">${avatar(byId(a.bot))}<div class="activity-copy"><time>${esc(a.time)}</time><strong>${esc(byId(a.bot).name)}</strong><p>${esc(a.text)}</p><button class="activity-chip" data-action="${a.icon==='layout'?'review':'activity-detail'}" data-id="${a.icon==='layout'?'design':a.bot}">${icon(a.icon)}${esc(a.chip)}</button></div></div>`).join('')}</div><hr class="panel-divider"><div class="panel-heading"><h2>A little nudge</h2><span>${pending().length} pending</span></div>${pending().length?`<div class="approval-mini"><div class="approval-label">${icon('clock')} Waiting on your good judgment</div><h3>${esc(pending()[0].title)}</h3><p>${esc(byId(pending()[0].bot).name)} has something ready for you.</p><button data-action="review" data-id="${pending()[0].id}">Take a look ${icon('arrow')}</button></div>`:`<div class="approval-mini"><div class="approval-label">${icon('check')} You’re all caught up</div><p style="margin-top:9px">The team has what it needs. Nice.</p></div>`}<hr class="panel-divider"><div class="panel-heading"><h2>The daily pulse</h2><span>Sample day</span></div><div class="pulse-stats"><strong>24</strong><span>little wins from the team</span></div><div class="bar-chart" role="img" aria-label="Illustrative team activity through the day">${[18,27,19,37,25,36,31,49,39,53,42,57,46,52,42,56].map(n=>`<i style="height:${n}px"></i>`).join('')}</div><div class="chart-axis"><span>9 AM</span><span>12 PM</span><span>3 PM</span><span>Now</span></div><div class="panel-note">${icon('heart')}Big ideas. Small steps.<br>A team that’s in your corner.</div>`;}
function firstMessage(b){let text=b.id==='focx'?`Hey Ryan. The den’s in a good place.\n\nByte is bringing the Connect welcome flow to life, Scout has a few interesting launch leads, and Pixel has something ready for your eye.\n\nWant the quick rundown, or shall we get something moving?`:`Hey Ryan, ${b.name} here. ${b.bio}\n\n${b.status==='waiting'?'I have a new welcome flow ready for your feedback. Want to take a look?':b.status==='idle'?'The last quality pass is complete. What should I take a look at next?':`Right now I’m ${b.doing.toLowerCase()}. What can I help you with?`}`;return {role:'bot',text,time:'Now',attachment:b.id==='pixel'?'design':b.id==='focx'?'plan':null};}
function chat(){const b=byId(selectedBot);if(!b.messages.length)b.messages.push(firstMessage(b));$('#main').innerHTML=`<div class="chat-header">${avatar(b)}<div><h1>${esc(b.name)}</h1><p>${esc(b.role)} <span style="color:#4a5057">/</span> ${esc(b.model)}</p></div><span class="live-tag"><i class="status-dot ${b.status}"></i>${b.status==='working'?'On it':b.status==='waiting'?'Ready for you':'Available'}</span></div><div class="chat-messages" id="chat-messages"><div class="chat-date">TODAY · DEMO CONVERSATION</div>${b.messages.map(m=>messageHTML(m,b)).join('')}${typing.has(b.id)?`<div class="typing"><i></i> ${esc(b.name)} is thinking…</div>`:''}</div>${composer(b)}`;scrollChat();}
function messageHTML(m,b){return `<div class="message ${m.role}">${m.role==='bot'?avatar(b):''}<div class="message-content"><div class="message-meta">${esc(b.name)}<span>${esc(m.time||'Now')}</span></div><p>${esc(m.text)}</p>${m.attachment?`<button class="message-attachment" data-action="review" data-id="${m.attachment}">${icon('file')}<div><strong>${esc(approvals.find(a=>a.id===m.attachment)?.doc||'Team brief')}</strong><span>Draft · Ready for review</span></div>${icon('chevron')}</button>`:''}${m===b.messages[0]?`<div class="suggestions"><button data-prompt="Give me a quick update">Give me a quick update</button><button data-prompt="What needs my attention?">What needs my attention?</button><button data-prompt="Plan the next steps for Connect">Plan the next steps</button></div>`:''}</div></div>`;}
function computerHTML(b,expanded=false){return `<div class="computer"><div class="computer-chrome"><i></i><i></i><i></i><span>${esc(b.name.toLowerCase())}@focx · workspace</span>${icon('screen')}</div><div class="computer-screen"><div class="terminal-label">${esc(b.name.toLowerCase())} / ${b.id==='byte'?'connect':b.id==='pixel'?'design-studio':b.id==='scout'?'research':'workspace'}</div>${b.id==='byte'?'<div class="code-line muted">// A warm welcome to Connect</div><div class="code-line"><span>export function</span> Welcome() {</div><div class="code-line">&nbsp; return (</div><div class="code-line">&nbsp;&nbsp; &lt;WelcomeFlow</div><div class="code-line">&nbsp;&nbsp;&nbsp; theme="focx"</div><div class="code-line">&nbsp;&nbsp; /&gt;</div><div class="code-line">&nbsp; );</div><div class="code-line">}</div>':`<div class="code-line"><span>✓</span> Team context loaded</div><div class="code-line"><span>✓</span> Connect priorities reviewed</div><div class="code-line"><span>✓</span> ${esc(b.id==='pixel'?'Design components checked':b.id==='patch'?'Quality checklist complete':'Working notes organized')}</div><div class="code-line muted">&nbsp;</div><div class="code-line">${esc(b.doing)}…</div>`}<div class="code-line muted" style="margin-top:12px">${screenTaken?'Control handed to you':paused?'Simulation paused':'Demo workspace'} <span class="cursor"></span></div></div><div class="computer-controls"><small>${screenTaken?'You have control':'Simulated computer'}</small><button data-action="${expanded?'takeover':'screen'}">${icon(expanded?'screen':'expand')}${expanded?(screenTaken?'Hand back':'Take control'):'Expand'}</button></div></div>`;}
function botPanel(){const b=byId(selectedBot);$('#activity').innerHTML=`<div class="panel-heading"><h2>${esc(b.name)}’s computer</h2><span class="pulse-icon"><i></i><i></i><i></i></span></div>${computerHTML(b)}<p class="section-note">A peek at what ${esc(b.name)} is working on.</p><div class="panel-subheading">A LITTLE ABOUT ${esc(b.name.toUpperCase())}</div><p class="bot-bio">${esc(b.bio)}</p><div class="panel-subheading">IN THE TOOLBOX</div><span class="skill-pill">${icon(b.skill)}${esc(b.role)}</span><span class="skill-pill">${icon('globe')}Browser</span><span class="skill-pill">${icon('file')}Working memory</span><button class="subtle-button wide-button" data-action="teach-skill" style="margin-top:9px">${icon('plus')}Teach a skill</button><div class="panel-subheading">UP NEXT</div>${tasks.filter(t=>t.bot===b.id&&t.status!=='done').slice(0,2).map(t=>`<button class="message-attachment" data-view="tasks">${icon('tasks')}<div><strong>${esc(t.title)}</strong><span>${t.status==='doing'?'In progress':'In the queue'}</span></div></button>`).join('')||'<p class="section-note">A little breathing room. Send a new task.</p>'}<hr class="panel-divider"><button class="subtle-button wide-button" data-action="bot-toggle">${icon(b.status==='idle'?'play':'pause')}${b.status==='idle'?'Wake up':'Give a break'}</button>`;}
function taskView(){ $('#main').innerHTML=`<div class="main-content">${heading('Little steps. Real progress.','Everything your team is moving forward.','THE TASK BOARD')}<div class="task-board">${[['todo','Up next'],['doing','In motion'],['done','All done']].map(([id,title])=>`<section class="board-column"><div class="column-heading"><i class="status-dot ${id==='todo'?'idle':id==='doing'?'waiting':''}"></i>${title}<span>${tasks.filter(t=>t.status===id).length}</span></div>${tasks.filter(t=>t.status===id).map(t=>`<article class="task-card"><small>FCX-${t.id}</small><h3>${esc(t.title)}</h3><div class="task-bottom">${avatar(byId(t.bot))}${esc(byId(t.bot).name)}${t.priority==='High'?'<span class="priority">Priority</span>':''}</div><select aria-label="Status for ${esc(t.title)}" data-task-status="${t.id}">${[['todo','Up next'],['doing','In motion'],['done','All done']].map(([v,l])=>`<option value="${v}" ${v===t.status?'selected':''}>${l}</option>`).join('')}</select></article>`).join('')||'<div class="empty-column">A clear little corner.<br>Ready for what’s next.</div>'}</section>`).join('')}</div><p class="section-note">Move a task with its status menu. This demo keeps your changes until you reload.</p></div>`;}
function inboxView(){ $('#main').innerHTML=`<div class="main-content">${heading('A second pair of eyes.','A few things are better with your good judgment.','YOUR INBOX',`<span class="live-tag">${pending().length} to review</span>`)}<div class="stack">${approvals.map(a=>`<article class="inbox-card">${avatar(byId(a.bot))}<div class="inbox-body"><div class="eyebrow" style="font-size:9px">${esc(byId(a.bot).name.toUpperCase())} · ${esc(a.label.toUpperCase())}</div><h3>${esc(a.title)}</h3><p>${esc(a.description)}</p>${a.status==='pending'?`<div class="actions"><button class="outline-button" data-action="review" data-id="${a.id}">${icon('file')}Open draft</button><button class="primary-button" data-action="approve" data-id="${a.id}">${icon('check')}Approve</button></div>`:`<div class="resolved-label">${icon(a.status==='approved'?'check':'chat')}${a.status==='approved'?'Approved · Team notified in this demo':'Feedback sent · Back with the team'}</div>`}</div></article>`).join('')}</div><p class="section-note">Approvals update the mockup. No messages, designs, or code are published.</p></div>`;}
function routineView(){ $('#main').innerHTML=`<div class="main-content">${heading('A rhythm of their own.','Good habits for a team that keeps things moving.','ROUTINES')}<div class="stack">${routines.map(r=>`<article class="routine-card"><div class="routine-icon">${icon(r.icon)}</div><div class="routine-body"><h3>${esc(r.name)}</h3><p>${esc(r.prompt)}</p><small>${esc(r.schedule)} <span style="color:#4c5259">·</span> ${esc(byId(r.bot).name)} ${r.enabled?'':'· Paused'}</small></div><button class="switch" role="switch" aria-checked="${r.enabled}" aria-label="Enable ${esc(r.name)}" data-action="toggle-routine" data-id="${r.id}"><i></i></button></article>`).join('')}</div><button class="outline-button" data-action="add-routine" style="align-self:flex-start">${icon('plus')}Give the team a new rhythm</button><p class="section-note">Routine schedules are simulated. They won’t run outside this mockup.</p></div>`;}
function connectionView(){ $('#main').innerHTML=`<div class="main-content">${heading('A well-stocked toolbox.','Your team’s favorite places to get things done.','CONNECTIONS')}<div class="connection-grid">${connections.map(c=>`<article class="connection-card">${icon(c.icon)}<h3>${c.name}</h3><p>${c.description}</p><button class="outline-button ${c.connected?'connected':''}" data-action="toggle-connection" data-id="${c.id}">${icon(c.connected?'check':'plus')}${c.connected?'Connected in demo':'Connect in demo'}</button></article>`).join('')}</div><p class="section-note">These are demo connections. No external accounts or services are accessed.</p></div>`;}
function settingsView(){ $('#main').innerHTML=`<div class="main-content">${heading('Make yourself at home.','Small adjustments for your corner of the internet.','PREFERENCES')}<div><div class="settings-row"><div><h3>A little personality</h3><p>Let your foxes bob, breathe, and do their thing.</p></div><button class="switch" role="switch" aria-checked="${motion}" aria-label="Animate bot avatars" data-action="toggle-motion"><i></i></button></div><div class="settings-row"><div><h3>Live demo activity</h3><p>Rotate the simulated feed while you explore.</p></div><button class="switch" role="switch" aria-checked="${!paused}" aria-label="Live demo activity" data-action="toggle-live"><i></i></button></div><div class="settings-row"><div><h3>Workspace</h3><p>Focx · Ryan’s personal den</p></div><span class="live-tag">Interactive demo</span></div><div class="settings-row"><div><h3>A fresh start</h3><p>Reload the original team, tasks, and conversations.</p></div><button class="outline-button" data-action="reset">Reset demo</button></div></div><p class="section-note">Built as a browser-based desktop mockup. Chat replies, computers, and agent activity are simulated.</p><button class="outline-button" data-action="about" style="align-self:flex-start">About Focx Bot ${icon('arrow')}</button></div>`;}
function render(){sidebar();toolbar();({den,chat,tasks:taskView,inbox:inboxView,routines:routineView,connections:connectionView,settings:settingsView}[view]||den)();if(view==='chat')botPanel();else activityPanel();document.body.classList.toggle('paused',paused);document.body.classList.toggle('no-motion',!motion);$('#global-status').textContent=paused?'The den is taking a breather':'The den is humming';document.title=`Focx Bot — ${view==='chat'?byId(selectedBot).name:view==='den'?'The den':view[0].toUpperCase()+view.slice(1)}`;}
function navigate(v,bot){view=v;if(bot)selectedBot=bot;attachNext=false;$('#sidebar').classList.remove('open');render();$('#main').scrollTop=0;}
function scrollChat(){requestAnimationFrame(()=>{const m=$('#chat-messages');if(m)m.scrollTop=m.scrollHeight;});}
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),3200);}
function modal(title,body,cls=''){const d=$('#modal');d.className=cls;$('#modal-content').innerHTML=`<div class="modal-head"><h2>${title}</h2><button class="icon-button" data-action="close-modal" aria-label="Close dialog">${icon('close')}</button></div><div class="modal-body">${body}</div>`;if(!d.open)d.showModal();}
function closeModal(){$('#modal').close();}
function botOptions(id=''){return bots.map(b=>`<option value="${b.id}" ${b.id===id?'selected':''}>${esc(b.name)} · ${esc(b.role)}</option>`).join('');}
function addBot(){avatarChoice=0;modal('A new face in the den.',`<p>A name, a specialty, a little personality. Your next teammate starts here.</p><form id="add-bot-form" class="form-fields"><label>Pick a personality<div class="avatar-select">${bots.slice(0,6).map(b=>`<button type="button" class="avatar-option ${b.avatar===0?'selected':''}" data-avatar="${b.avatar}" aria-label="${esc(b.name)} avatar" aria-pressed="${b.avatar===0}">${avatar(b)}</button>`).join('')}</div></label><label>Name<input name="name" placeholder="e.g. Ember" required maxlength="24" autofocus></label><label>What’s their specialty?<input name="role" placeholder="e.g. Customer happiness" required maxlength="40"></label><label>Model<select name="model"><option>Claude</option><option>Codex</option><option>Grok</option></select></label><button class="primary-button" type="submit">${icon('plus')}Welcome to the team</button></form>`);}
function addTask(){modal('Give a good idea a nudge.',`<p>What should the team take on next?</p><form id="add-task-form" class="form-fields"><label>Task<input name="title" placeholder="e.g. Plan a thoughtful launch for Connect" required maxlength="140" autofocus></label><label>Who’s on it?<select name="bot">${botOptions(selectedBot)}</select></label><label>Priority<select name="priority"><option>Normal</option><option>High</option></select></label><button class="primary-button" type="submit">${icon('plus')}Add to the queue</button></form>`);}
function addRoutine(){modal('Give it a rhythm.',`<p>Set up a sample routine for your team. Schedules are for this demo only.</p><form id="add-routine-form" class="form-fields"><label>Name<input name="name" placeholder="e.g. Friday’s little victories" required maxlength="70"></label><label>What should happen?<textarea name="prompt" placeholder="Summarize what we shipped and what we learned…" required maxlength="500"></textarea></label><label>Teammate<select name="bot">${botOptions()}</select></label><label>Schedule<select name="schedule"><option>Every weekday · 8:00 AM</option><option>Every day · 11:00 PM</option><option>Every Friday · 4:00 PM</option><option>Every Monday · 9:00 AM</option></select></label><button class="primary-button" type="submit">${icon('repeat')}Create demo routine</button></form>`);}
function review(id){const a=approvals.find(x=>x.id===id);if(!a)return;modal(a.doc,`<p>${esc(byId(a.bot).name)} · ${esc(a.label)} · ${a.status==='pending'?'Ready for your thoughts':esc(a.status)}</p><div class="doc-preview"><h3>${esc(a.title)}</h3><p>${esc(a.body)}</p></div>${a.status==='pending'?`<div style="display:flex;gap:9px;margin-top:20px"><button class="primary-button" data-action="approve" data-id="${a.id}">${icon('check')}Looks good</button><button class="outline-button" data-action="feedback" data-id="${a.id}">${icon('chat')}Send feedback</button></div>`:''}<button class="subtle-button" style="margin-top:15px" data-action="download" data-id="${a.id}">${icon('download')}Download draft</button>`);}
function approve(id){const a=approvals.find(x=>x.id===id);if(!a||a.status!=='pending')return;a.status='approved';const b=byId(a.bot);b.status='working';b.doing='Moving to the next step';log(a.bot,'Got your approval. Moving the plan forward.','Approved','check');closeModal();render();toast(`${b.name} got your okay. On to the next little win.`);celebrate();}
function celebrate(){if(!motion||matchMedia('(prefers-reduced-motion: reduce)').matches)return;for(let i=0;i<30;i++){const el=document.createElement('i');el.className='confetti';el.style.left=Math.random()*100+'vw';el.style.background=['#e6a471','#b9c79b','#b7a5cf','#97b8cd'][i%4];el.style.animationDelay=Math.random()*.4+'s';document.body.append(el);setTimeout(()=>el.remove(),3100);}}
function log(bot,text,chip='Task update',ic='tasks'){activity.unshift({bot,text,chip,icon:ic,time:'Just now'});activity=activity.slice(0,10);}
function search(){modal('Find your way.',`<input class="search-input" id="global-search" placeholder="A teammate, task, or place…" aria-label="Search workspace" autofocus><div class="search-results" id="search-results"></div>`);searchResults('');}
function searchResults(q){const s=q.toLowerCase();const bs=bots.filter(b=>(b.name+' '+b.role).toLowerCase().includes(s));const ts=tasks.filter(t=>t.title.toLowerCase().includes(s));$('#search-results').innerHTML=bs.map(b=>`<button class="search-result" data-bot="${b.id}">${avatar(b)}<div><strong>${esc(b.name)}</strong><small>${esc(b.role)}</small></div></button>`).join('')+ts.slice(0,5).map(t=>`<button class="search-result" data-view="tasks">${icon('tasks')}<div><strong>${esc(t.title)}</strong><small>FCX-${t.id} · ${esc(byId(t.bot).name)}</small></div></button>`).join('')+['den','inbox','tasks','routines','connections','settings'].filter(v=>v.includes(s)).map(v=>`<button class="search-result" data-view="${v}">${icon(v==='den'?'home':v==='routines'?'repeat':v==='connections'?'plug':v)}<strong>${v==='den'?'The den':v[0].toUpperCase()+v.slice(1)}</strong></button>`).join('');if(!$('#search-results').children.length)$('#search-results').innerHTML='<p class="section-note" style="padding:15px">No matches yet. Try a teammate’s name or a task.</p>';}
async function sendMessage(text){if(!text.trim())return;const b=view==='chat'?byId(selectedBot):bots[0];if(typing.has(b.id)){toast(`${b.name} is finishing a thought. One moment.`);return;}if(!b.messages.length)b.messages.push(firstMessage(b));const hadAttach=attachNext;attachNext=false;b.messages.push({role:'user',text:text.trim()+(hadAttach?'\n[Attached: Connect team brief]':''),time:'Now'});typing.add(b.id);navigate('chat',b.id);setTimeout(()=>{const reply=respond(b,text,hadAttach);b.messages.push({role:'bot',...reply,time:'Now'});typing.delete(b.id);if(view==='chat'&&selectedBot===b.id){chat();botPanel();}sidebar();toolbar();},1250);}
function respond(b,text,attached){const lower=text.toLowerCase();if(attached)return {text:'I’ve got the Connect team brief. It covers a focused welcome flow, consistent Focx components, and a thoughtful launch.\n\nI’d start by resolving Pixel’s welcome-flow review, then hand that direction to Byte. Want to review the draft?',attachment:'plan'};
 if(/hello|^hi\b|hey|thanks|thank you/.test(lower))return {text:`${/thank/.test(lower)?'You’re welcome, Ryan.':'Hey Ryan. Good to see you in the den.'} A small team can do a lot with a little direction.\n\nI can share a status update, help you review a draft, or queue a task. What’s on your mind?`};
 if(/attention|review|approve|feedback|draft/.test(lower)){const a=pending().find(x=>x.bot===b.id)||pending()[0];return a?{text:`${byId(a.bot).name} has “${a.title}” ready.\n\n${a.description}\n\nOpen the draft below to approve it or send feedback. There ${pending().length===1?'is':'are'} ${pending().length} pending ${pending().length===1?'review':'reviews'} in your inbox.`,attachment:a.id}:{text:'You’re all caught up. No reviews are waiting on you.\n\nThe next useful move is to pick one task from the queue and give it a clear finish line.'};}
 if(/status|update|rundown|happening|progress/.test(lower)){return {text:b.id==='focx'?`Here’s the pulse of the den:\n\n${bots.filter(x=>x.id!=='focx').map(x=>`${x.name} — ${x.doing}.`).join('\n')}\n\n${done()} tasks done, ${tasks.filter(t=>t.status==='doing').length} in motion, and ${pending().length} ready for your review. We’re keeping the focus on Connect.`:`Here’s my corner of the den: ${b.doing.toLowerCase()}.\n\n${tasks.filter(t=>t.bot===b.id).map(t=>`• ${t.title} — ${t.status==='done'?'complete':t.status==='doing'?'in progress':'queued'}`).join('\n')||'My queue is clear. Ready for your next idea.'}\n\nTell me what you’d like me to take on next.`};}
 if(/routine|every day|daily|weekly|every morning/.test(lower))return {text:'That sounds like a good rhythm for the team. Open Routines to choose a teammate, a schedule, and a clear prompt.\n\nFor Connect, I’d start with a morning brief: what shipped, what’s blocked, and the three decisions that need you.\n\nSchedules here are part of the mockup; nothing runs in the background.'};
 if(/next step|priorit|plan/.test(lower)&&!/create|assign|add a task/.test(lower))return {text:'I’d keep the next steps small and connected:\n\n1. Review Pixel’s welcome-flow draft.\n2. Let Byte build the approved direction.\n3. Have Patch check the complete first-use experience.\n4. Ask Bloom and Scout to prepare a focused launch experiment.\n\nOne polished path from “hello” to a meaningful first action. That’s a good next milestone.',attachment:'plan'};
 const title=text.trim().slice(0,140);let assignee=b;if(b.id==='focx'){if(/code|build|implement|bug|develop/.test(lower))assignee=byId('byte');else if(/design|figma|screen|visual/.test(lower))assignee=byId('pixel');else if(/market|launch|growth|campaign/.test(lower))assignee=byId('bloom');else if(/research|compet|explore/.test(lower))assignee=byId('scout');else if(/test|quality|check/.test(lower))assignee=byId('patch');}
 tasks.unshift({id:nextTask++,title,bot:assignee.id,status:'todo',priority:'Normal'});log(assignee.id,`A new task is in the queue: ${title}`,`FCX-${nextTask-1}`,'tasks');return {text:`${assignee.id===b.id?'I’ve added this to my queue':`I’ve put ${assignee.name} on this`}:\n\n“${title}”\n\nYou’ll find it on the task board as FCX-${nextTask-1}. Set its status to “In motion” when you’re ready.\n\nThis is a demo handoff — the task is queued in the mockup, without running an external agent.`};}
document.addEventListener('click',e=>{const el=e.target.closest('button');if(!el)return;if(el.dataset.view){closeModal();navigate(el.dataset.view);return;}if(el.dataset.bot){closeModal();navigate('chat',el.dataset.bot);return;}if(el.dataset.mode){denMode=el.dataset.mode;den();return;}if(el.dataset.prompt){sendMessage(el.dataset.prompt);return;}if(el.dataset.avatar!==undefined){avatarChoice=Number(el.dataset.avatar);document.querySelectorAll('.avatar-option').forEach(x=>{x.classList.toggle('selected',x===el);x.setAttribute('aria-pressed',x===el?'true':'false');});return;}
 const a=el.dataset.action,id=el.dataset.id;const bot=byId(selectedBot);switch(a){
 case 'menu':$('#sidebar').classList.toggle('open');break;
 case 'search':search();break;
 case 'add-bot':addBot();break;
 case 'add-task':addTask();break;
 case 'add-routine':addRoutine();break;
 case 'close-modal':closeModal();break;
 case 'review':review(id);break;
 case 'approve':approve(id);break;
 case 'feedback':modal('A little direction.',`<p>What would you like ${esc(byId(approvals.find(x=>x.id===id).bot).name)} to change?</p><form id="feedback-form" data-id="${id}" class="form-fields"><label>Your feedback<textarea name="feedback" required maxlength="1000" placeholder="Keep the calm tone, but make the first action clearer…" rows="4"></textarea></label><button class="primary-button" type="submit">Send demo feedback ${icon('arrow')}</button></form>`);break;
 case 'download':{const d=approvals.find(x=>x.id===id);const blob=new Blob([d.doc+'\n\n'+d.body],{type:'text/plain'});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download='focx-'+id+'-draft.txt';link.click();setTimeout(()=>URL.revokeObjectURL(url),500);toast('Draft downloaded.');break;}
 case 'toggle-live':paused=!paused;document.body.classList.toggle('paused',paused);toolbar();if(view==='den')den();if(view==='settings')settingsView();$('#global-status').textContent=paused?'The den is taking a breather':'The den is humming';if(view==='chat')botPanel();toast(paused?'A little breather. Demo activity paused.':'Back in the groove.');break;
 case 'toggle-motion':motion=!motion;document.body.classList.toggle('no-motion',!motion);settingsView();break;
 case 'toggle-routine':{const r=routines.find(r=>r.id===Number(id));r.enabled=!r.enabled;routineView();toast(`${r.name}: ${r.enabled?'enabled in demo':'paused'}.`);break;}
 case 'toggle-connection':{const c=connections.find(c=>c.id===id);c.connected=!c.connected;connectionView();toast(`${c.name} ${c.connected?'connected':'disconnected'} in demo.`);break;}
 case 'attach':attachNext=!attachNext;if($('#attach-label'))$('#attach-label').textContent=attachNext?'Brief attached':'';toast(attachNext?'Sample Connect team brief attached.':'Brief removed.');break;
 case 'choose-target':modal('Who’s on your mind?',`<div class="search-results">${bots.map(b=>`<button class="search-result" data-bot="${b.id}">${avatar(b)}<div><strong>${esc(b.name)}</strong><small>${esc(b.role)}</small></div></button>`).join('')}</div>`);break;
 case 'invite-info':navigate('chat','focx');break;
 case 'screen':modal(`${esc(bot.name)}’s computer`,`${computerHTML(bot,true)}<p class="section-note">A simulated workspace. Take control to try the handoff interaction.</p>`,'computer-expanded');break;
 case 'takeover':screenTaken=!screenTaken;modal(`${esc(bot.name)}’s computer`,`${computerHTML(bot,true)}${screenTaken?'<form id="computer-form" class="form-fields"><label>Try a local demo command<input name="command" placeholder="Try: status, help, or ls" required autocomplete="off"></label><button class="outline-button" type="submit">Run demo command</button></form><p class="section-note" id="computer-output" style="margin-top:14px"></p>':'<p class="section-note">The bot has the wheel again.</p>'}`,'computer-expanded');if(view==='chat')botPanel();break;
 case 'teach-skill':modal(`Teach ${esc(bot.name)} a skill.`,`<p>Write a reusable instruction for your teammate. Saved in this demo session.</p><form id="skill-form" class="form-fields"><label>Skill name<input name="name" required maxlength="60" placeholder="e.g. Write in the Focx voice"></label><label>How should it work?<textarea name="instructions" required maxlength="2000" rows="4" placeholder="Use a warm, thoughtful tone. Keep it clear and human…"></textarea></label><button class="primary-button" type="submit">${icon('spark')}Save the skill</button></form>`);break;
 case 'bot-toggle':bot.status=bot.status==='idle'?'working':'idle';bot.doing=bot.status==='idle'?'Taking a little break':'Ready for the next task';render();toast(bot.status==='idle'?`${bot.name} is taking a breather.`:`${bot.name} is back in the den.`);break;
 case 'activity-detail':navigate('chat',id);break;
 case 'workspace':modal('Your corner of the internet.',`<p>Focx workspace · Ryan’s personal den</p><div class="doc-preview"><h3>${bots.length} teammates, one direction.</h3><p>Connect is the team’s focus. Product, design, research, growth, and quality — all in one little den.</p></div><button class="primary-button" data-view="den">Back to the den ${icon('arrow')}</button>`);break;
 case 'about':modal('Meet Focx Bot.',`<p>A playful desktop home for your AI teammates.</p><div class="doc-preview"><h3>Small team. Big thinkers.</h3><p>Chat with a fox, assign a task, review a draft, or peek at a bot’s computer. Your changes stay in this browser session and reset when the page reloads.\n\nAll conversations, activity, schedules, and connections are simulated. No real AI service is connected.</p></div><p class="section-note" style="margin-top:17px">Interaction inspiration: <a href="https://x.ai/news/designing-grok-bot" target="_blank" rel="noopener noreferrer">Grok Bot’s persistent teammates</a>. Focx Bot is an independent concept.</p>`);break;
 case 'reset':modal('A fresh little start?',`<p>This will reset your demo tasks, conversations, teammates, and preferences.</p><button class="primary-button" data-action="confirm-reset">Reset the demo</button>`);break;
 case 'confirm-reset':location.reload();break;
 }});
document.addEventListener('submit',e=>{e.preventDefault();const f=e.target,data=new FormData(f);switch(f.id){
 case 'chat-form':{const text=$('#message-input').value;sendMessage(text);break;}
 case 'add-bot-form':{const template=bots[avatarChoice]||bots[0];const name=String(data.get('name')).trim(),role=String(data.get('role')).trim();if(!name||!role)return;const b=makeBot('bot-'+Date.now(),name,role,avatarChoice,template.color,'idle','Ready for a little adventure',template.skill,`I’m ${name}, your ${role.toLowerCase()} teammate. I’m ready to help move Connect forward, one thoughtful step at a time.`);b.model=String(data.get('model'));bots.push(b);closeModal();navigate('chat',b.id);toast(`${b.name} found a home in the den.`);celebrate();break;}
 case 'add-task-form':{const title=String(data.get('title')).trim();if(!title)return;const botId=String(data.get('bot'));tasks.unshift({id:nextTask++,title,bot:botId,status:'todo',priority:String(data.get('priority'))});log(botId,`A new task is in the queue: ${title}`,`FCX-${nextTask-1}`,'tasks');closeModal();navigate('tasks');toast(`${byId(botId).name} has a new task in the queue.`);break;}
 case 'add-routine-form':{const name=String(data.get('name')).trim(),prompt=String(data.get('prompt')).trim();if(!name||!prompt)return;routines.push({id:Date.now(),name,prompt,schedule:String(data.get('schedule')),bot:String(data.get('bot')),enabled:true,icon:'repeat'});closeModal();navigate('routines');toast('A new rhythm, saved in your demo.');break;}
 case 'feedback-form':{const a=approvals.find(x=>x.id===f.dataset.id);const feedback=String(data.get('feedback')).trim();if(!feedback)return;a.status='feedback';const b=byId(a.bot);if(!b.messages.length)b.messages.push(firstMessage(b));b.messages.push({role:'user',text:`Feedback on “${a.title}”: ${feedback}`},{role:'bot',text:'Thanks, Ryan. I’ve captured that direction in our demo conversation. I’ll use it as the brief for the next pass.'});b.status='working';b.doing='Taking your feedback on board';log(b.id,'Your feedback is captured for the next pass.','Feedback received','chat');closeModal();navigate('chat',b.id);toast('Your feedback is with the team.');break;}
 case 'skill-form':{const b=byId(selectedBot);const name=String(data.get('name')).trim(),instructions=String(data.get('instructions')).trim();if(!name||!instructions)return;if(!b.skills)b.skills=[];b.skills.push({name,instructions});closeModal();botPanel();toast(`${b.name} learned “${name}” in this demo.`);break;}
 case 'computer-form':{const cmd=String(data.get('command')).trim().toLowerCase();const replies={help:'Try status to check the workspace, or ls to see the sample files.',status:'Workspace ready. You have control. This computer is simulated.',ls:'connect-brief.md    team-priorities.md    welcome-flow.tsx'};$('#computer-output').textContent=replies[cmd]||'Demo command not found. Try help, status, or ls.';break;}
 }});
document.addEventListener('input',e=>{if(e.target.id==='global-search')searchResults(e.target.value);});
document.addEventListener('change',e=>{if(e.target.dataset.taskStatus){const t=tasks.find(t=>t.id===Number(e.target.dataset.taskStatus));const previous=t.status;t.status=e.target.value;log(t.bot,`${t.title} ${t.status==='done'?'is complete.':t.status==='doing'?'is in motion.':'is back in the queue.'}`,`FCX-${t.id}`,t.status==='done'?'check':'tasks');render();if(t.status==='done'&&previous!=='done'){toast('One more little win. Nice work.');celebrate();}else toast('Task updated.');}});
document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();search();}if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing&&e.target.id==='message-input'){e.preventDefault();sendMessage(e.target.value);}});
$('#modal').addEventListener('click',e=>{if(e.target===$('#modal')){const r=$('#modal').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeModal();}});
const originalBotPanel=botPanel;botPanel=function(){originalBotPanel();const b=byId(selectedBot);if(b.skills?.length){const target=$('#activity .panel-subheading');const block=document.createElement('div');block.innerHTML='<div class="panel-subheading">LEARNED SKILLS</div>'+b.skills.map((s,i)=>`<button class="skill-pill" data-skill="${i}">${icon('spark')}${esc(s.name)}</button>`).join('');target.before(block);block.querySelectorAll('[data-skill]').forEach(btn=>btn.onclick=()=>{const s=b.skills[Number(btn.dataset.skill)];modal(esc(s.name),`<div class="doc-preview"><p>${esc(s.instructions)}</p></div><p class="section-note" style="margin-top:14px">Saved for ${esc(b.name)} in this demo session.</p>`);});}};
let tick=0;const demoEvents=[['byte','Checking the welcome flow against the brief.','Working notes','code'],['scout','Organizing the launch research into a shortlist.','Research notes','file'],['bloom','Shaping a small, focused launch experiment.','Launch plan','trend'],['focx','Keeping the next steps in a sensible order.','Team priorities','tasks']];
setInterval(()=>{if(paused||document.hidden)return;const event=demoEvents[tick++%demoEvents.length];const b=byId(event[0]);if(b.status!=='working')return;log(...event);if(view!=='chat')activityPanel();},24000);
render();
